// ═══════════════════════════════════════════════════
// Vehicles feature — configuration
// ═══════════════════════════════════════════════════

/**
 * Show the "Simulated city network" badge wherever simulated journeys are
 * displayed. The camera clips are real Mumbai traffic footage
 * pinned to the junctions they were plausibly shot at, so cross-camera
 * journeys are simulated; flip this to `false`
 * to hide the badge everywhere at once.
 */
export const SHOW_SIMULATION_BADGE = true;

/** Static simulation outputs (generated by pipeline/simulation, served from public/). */
export const SIM_JOURNEYS_URL = '/sim/journeys.json';
export const SIM_ROUTES_URL = '/sim/road_routes.json';
export const SIM_SUMMARY_URL = '/sim/summary.json';

/** A gap between two sightings longer than this starts a new trip (Supabase data). */
export const TRIP_GAP_SECONDS = 45 * 60;

/** Implied speed above which two sightings of one plate are physically impossible. */
export const IMPOSSIBLE_SPEED_KMPH = 120;
