// ═══════════════════════════════════════════════════
// AUTO-GENERATED by pipeline/simulation/export_demo_fixtures.py from
// public/sim/summary.json + journeys.json — do not edit by hand; re-run the
// script after re-simulating. Cross-checked by src/features/alerts/fixtures.test.ts.
// ═══════════════════════════════════════════════════

/* eslint-disable */

/** Simulated day (IST). */
export const SIM_DATE = "2026-09-29";

/** Curated watchlist plates (summary.json demo.watchlist order). */
export const SIM_WATCHLIST = [
  {"plate_text": "MH 01 CS 0126", "vehicle_type": "car", "plate_variant": "private", "category": "stolen", "priority": "critical", "reason": "Reported stolen from Jogeshwari East (simulated FIR, MIDC police station)"},
  {"plate_text": "MH 02 EG 9588", "vehicle_type": "car", "plate_variant": "private", "category": "wanted", "priority": "high", "reason": "Linked to chain-snatching cases along LBS Marg (simulated)"},
  {"plate_text": "MH 03 CM 7501", "vehicle_type": "car", "plate_variant": "private", "category": "flagged", "priority": "medium", "reason": "Repeated signal-jumping e-challans at Sion Circle (simulated)"},
  {"plate_text": "MH 47 EL 9660", "vehicle_type": "car", "plate_variant": "private", "category": "missing", "priority": "high", "reason": "Vehicle of a missing person report, Dadar police (simulated)"},
] as const;

/** Every sighting of a watchlist plate: [watchlist index, journey id, sighting index, camera code, IST time]. */
export const SIM_WATCH_HITS: [number, string, number, string, string][] = [
  [0, "J00428", 0, "JG-01", "08:05:00"],
  [0, "J00428", 1, "AN-01", "08:11:42"],
  [0, "J00428", 2, "VP-01", "08:18:24"],
  [0, "J00428", 3, "SC-01", "08:22:22"],
  [0, "J00428", 4, "DD-01", "08:52:12"],
  [0, "J02591", 0, "DD-01", "18:40:05"],
  [0, "J02591", 1, "SN-01", "18:49:16"],
  [0, "J02591", 2, "KR-01", "19:17:17"],
  [0, "J02591", 3, "BH-01", "19:43:48"],
  [1, "J00328", 0, "BH-01", "07:30:01"],
  [1, "J00328", 1, "KR-01", "07:50:29"],
  [1, "J00328", 2, "SN-01", "08:09:49"],
  [1, "J00328", 3, "DD-01", "08:21:21"],
  [1, "J01514", 0, "DD-01", "13:10:04"],
  [1, "J01514", 1, "SC-01", "13:30:02"],
  [1, "J01514", 2, "VP-01", "13:33:34"],
  [1, "J03059", 0, "VP-01", "20:15:32"],
  [1, "J03059", 1, "AN-01", "20:21:10"],
  [1, "J03059", 2, "JG-01", "20:26:34"],
  [1, "J03059", 3, "BH-01", "20:59:50"],
  [2, "J01180", 0, "SN-01", "10:20:27"],
  [2, "J01180", 1, "KR-01", "10:41:17"],
  [2, "J01180", 2, "SC-01", "10:51:11"],
  [2, "J01985", 0, "SC-01", "16:45:46"],
  [2, "J01985", 1, "VP-01", "16:51:13"],
  [2, "J01985", 2, "AN-01", "16:56:58"],
  [2, "J01985", 3, "JG-01", "17:03:45"],
  [3, "J00249", 0, "DD-01", "06:50:26"],
  [3, "J00249", 1, "SC-01", "07:12:47"],
  [3, "J00249", 2, "VP-01", "07:16:19"],
  [3, "J00249", 3, "AN-01", "07:21:26"],
  [3, "J01363", 0, "AN-01", "11:30:31"],
  [3, "J01363", 1, "VP-01", "11:36:13"],
  [3, "J01363", 2, "SC-01", "11:38:26"],
  [3, "J01363", 3, "KR-01", "11:47:28"],
  [3, "J01363", 4, "BH-01", "12:03:28"],
  [3, "J02750", 0, "BH-01", "19:05:48"],
  [3, "J02750", 1, "JG-01", "19:58:37"],
];

/** Route anomalies (summary.json demo.anomalies); the alert fires at the last evidence sighting. */
export const SIM_ANOMALIES = [
  {"kind": "cloned_plate", "plate_text": "MH 04 AK 4356", "journey": "J00755", "index": 0, "camera_code": "BH-01", "time": "09:01:16", "evidence": [["DD-01", "08:58:12"], ["BH-01", "09:01:16"]], "reason": "Possible cloned plate: read at Dadar TT Junction and Bhandup LBS Marg 3 min apart; 18.2 km by road needs ~36 min (implied 356 km/h)"},
  {"kind": "circling", "plate_text": "MH 05 DN 0114", "journey": "J03177", "index": 6, "camera_code": "VP-01", "time": "21:24:57", "evidence": [["VP-01", "21:05:39"], ["SC-01", "21:08:19"], ["VP-01", "21:12:27"], ["SC-01", "21:15:14"], ["VP-01", "21:18:51"], ["SC-01", "21:21:36"], ["VP-01", "21:24:57"]], "reason": "Suspicious circling: looped Vile Parle Flyover and Santacruz Airport Approach 3 times in 19 min with no destination"},
] as const;

/** Newest ANPR reads up to 2026-09-29T20:59:50+05:30 (the last watchlist hit), newest first. */
export const SIM_LIVE_FEED = [
  {"id": "lf-J03059-3", "plate": "MH 02 EG 9588", "cameraCode": "BH-01", "cameraName": "Bhandup LBS Marg", "vehicleType": "car", "plateVariant": "private", "confidence": 98, "secondsAgo": 0, "watchlist": "high"},
  {"id": "lf-J03147-1", "plate": "MH 01 UC 0318", "cameraCode": "AN-01", "cameraName": "Andheri Flyover (Gundavali)", "vehicleType": "car", "plateVariant": "private", "confidence": 95, "secondsAgo": 25, "watchlist": null},
  {"id": "lf-J03121-1", "plate": "MH 04 FS 7251", "cameraCode": "DD-01", "cameraName": "Dadar TT Junction", "vehicleType": "car", "plateVariant": "private", "confidence": 91, "secondsAgo": 39, "watchlist": null},
  {"id": "lf-J03152-1", "plate": "MH 43 WW 6095", "cameraCode": "AN-01", "cameraName": "Andheri Flyover (Gundavali)", "vehicleType": "motorcycle", "plateVariant": "private", "confidence": 85, "secondsAgo": 49, "watchlist": null},
  {"id": "lf-J03097-2", "plate": "MH 43 EN 3782", "cameraCode": "DD-01", "cameraName": "Dadar TT Junction", "vehicleType": "car", "plateVariant": "private", "confidence": 84, "secondsAgo": 51, "watchlist": null},
  {"id": "lf-J03143-1", "plate": "MH 02 BZ 8639", "cameraCode": "DD-01", "cameraName": "Dadar TT Junction", "vehicleType": "motorcycle", "plateVariant": "private", "confidence": 94, "secondsAgo": 51, "watchlist": null},
  {"id": "lf-J03150-1", "plate": "MH 01 RT 0711", "cameraCode": "AN-01", "cameraName": "Andheri Flyover (Gundavali)", "vehicleType": "car", "plateVariant": "private", "confidence": 97, "secondsAgo": 63, "watchlist": null},
  {"id": "lf-J03128-2", "plate": "MH 04 MS 4035", "cameraCode": "KR-01", "cameraName": "Kurla Depot Junction", "vehicleType": "car", "plateVariant": "private", "confidence": 86, "secondsAgo": 95, "watchlist": null},
] as const;

/** Sample pipeline plate reads per camera (plates really seen at that camera). */
export const SIM_CAMERA_READS = [
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 01 CS 0126", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.73, "frame_sec": 3.8},
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 14 XJ 0057", "vehicle_type": "motorcycle", "plate_variant": "private", "confidence": 0.9, "frame_sec": 8.8},
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 43 BM 3816", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.73, "frame_sec": 11.7},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "MH 47 EL 9660", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.75, "frame_sec": 4.4},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "MH 03 ZQ 2351", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.74, "frame_sec": 8.4},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "KA 53 TZ 0148", "vehicle_type": "motorcycle", "plate_variant": "private", "confidence": 0.83, "frame_sec": 12.5},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 02 EG 9588", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.95, "frame_sec": 3.1},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 03 ZT 8025", "vehicle_type": "motorcycle", "plate_variant": "private", "confidence": 0.87, "frame_sec": 7.8},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 46 TW 1153", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.81, "frame_sec": 12.9},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 03 CM 7501", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.76, "frame_sec": 4.2},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 12 CE 8043", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.87, "frame_sec": 6.9},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 46 HH 7140", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.85, "frame_sec": 12.3},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "MH 04 AK 4356", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.92, "frame_sec": 3.1},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "MH 04 MR 1641", "vehicle_type": "bus", "plate_variant": "commercial", "confidence": 0.75, "frame_sec": 6.9},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "24 BH 0075 XC", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.92, "frame_sec": 12.5},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 02 A 8060", "vehicle_type": "car", "plate_variant": "commercial", "confidence": 0.74, "frame_sec": 3.6},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 02 JT 7764", "vehicle_type": "bus", "plate_variant": "ev", "confidence": 0.96, "frame_sec": 7.4},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 48 UG 2448", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.92, "frame_sec": 12.2},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "MH 04 MW 5723", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.82, "frame_sec": 2.1},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "MH 01 PL 8691", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.95, "frame_sec": 6.8},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "GJ 01 JK 6763", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.91, "frame_sec": 12.4},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 43 ZB 7217", "vehicle_type": "motorcycle", "plate_variant": "private", "confidence": 0.82, "frame_sec": 3.5},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 05 XN 8163", "vehicle_type": "motorcycle", "plate_variant": "private", "confidence": 0.84, "frame_sec": 8.5},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 48 BQ 8616", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.81, "frame_sec": 11.8},
] as const;
