// ═══════════════════════════════════════════════════
// AUTO-GENERATED by pipeline/simulation/export_demo_fixtures.py from
// public/sim/summary.json + journeys.json — do not edit by hand; re-run the
// script after re-simulating. Cross-checked by src/features/alerts/fixtures.test.ts.
// ═══════════════════════════════════════════════════

/* eslint-disable */

/** Simulated day (IST). */
export const SIM_DATE = "2026-09-29";

/** Curated watchlist plates (summary.json demo.watchlist order). */
export const SIM_WATCHLIST = [
  {"plate_text": "MH 01 CS 0126", "vehicle_type": "car", "plate_variant": "private", "category": "stolen", "priority": "critical", "reason": "Reported stolen from Jogeshwari East (simulated FIR, MIDC police station)"},
  {"plate_text": "MH 02 EG 9588", "vehicle_type": "car", "plate_variant": "private", "category": "wanted", "priority": "high", "reason": "Linked to chain-snatching cases along LBS Marg (simulated)"},
  {"plate_text": "MH 03 CM 7501", "vehicle_type": "car", "plate_variant": "private", "category": "flagged", "priority": "medium", "reason": "Repeated signal-jumping e-challans at Sion Circle (simulated)"},
  {"plate_text": "MH 47 EL 9660", "vehicle_type": "car", "plate_variant": "private", "category": "missing", "priority": "high", "reason": "Vehicle of a missing person report, Dadar police (simulated)"},
] as const;

/** Every sighting of a watchlist plate: [watchlist index, journey id, sighting index, camera code, IST time]. */
export const SIM_WATCH_HITS: [number, string, number, string, string][] = [
  [0, "J00448", 0, "JG-01", "08:05:00"],
  [0, "J00448", 1, "AN-01", "08:11:42"],
  [0, "J00448", 2, "VP-01", "08:18:24"],
  [0, "J00448", 3, "SC-01", "08:22:22"],
  [0, "J00448", 4, "DD-01", "08:52:12"],
  [0, "J02604", 0, "DD-01", "18:40:05"],
  [0, "J02604", 1, "SN-01", "18:49:16"],
  [0, "J02604", 2, "KR-01", "19:17:17"],
  [0, "J02604", 3, "BH-01", "19:43:48"],
  [1, "J00290", 0, "BH-01", "07:30:01"],
  [1, "J00290", 1, "KR-01", "07:50:29"],
  [1, "J00290", 2, "SN-01", "08:09:49"],
  [1, "J00290", 3, "DD-01", "08:21:21"],
  [1, "J01471", 0, "DD-01", "13:10:04"],
  [1, "J01471", 1, "SC-01", "13:30:02"],
  [1, "J01471", 2, "VP-01", "13:33:34"],
  [1, "J03063", 0, "VP-01", "20:15:32"],
  [1, "J03063", 1, "AN-01", "20:21:10"],
  [1, "J03063", 2, "JG-01", "20:26:34"],
  [1, "J03063", 3, "BH-01", "20:59:50"],
  [2, "J01136", 0, "SN-01", "10:20:27"],
  [2, "J01136", 1, "KR-01", "10:41:17"],
  [2, "J01136", 2, "SC-01", "10:51:11"],
  [2, "J01939", 0, "SC-01", "16:45:46"],
  [2, "J01939", 1, "VP-01", "16:51:13"],
  [2, "J01939", 2, "AN-01", "16:56:58"],
  [2, "J01939", 3, "JG-01", "17:03:45"],
  [3, "J00219", 0, "DD-01", "06:50:26"],
  [3, "J00219", 1, "SC-01", "07:12:47"],
  [3, "J00219", 2, "VP-01", "07:16:19"],
  [3, "J00219", 3, "AN-01", "07:21:26"],
  [3, "J01314", 0, "AN-01", "11:30:31"],
  [3, "J01314", 1, "VP-01", "11:36:13"],
  [3, "J01314", 2, "SC-01", "11:38:26"],
  [3, "J01314", 3, "KR-01", "11:47:28"],
  [3, "J01314", 4, "BH-01", "12:03:28"],
  [3, "J02761", 0, "BH-01", "19:05:48"],
  [3, "J02761", 1, "JG-01", "19:58:37"],
];

/** Route anomalies (summary.json demo.anomalies); the alert fires at the last evidence sighting. */
export const SIM_ANOMALIES = [
  {"kind": "cloned_plate", "plate_text": "MH 04 AK 4356", "journey": "J00735", "index": 0, "camera_code": "BH-01", "time": "09:01:16", "evidence": [["DD-01", "08:58:12"], ["BH-01", "09:01:16"]], "reason": "Possible cloned plate: read at Dadar TT Junction and Bhandup LBS Marg 3 min apart; 18.2 km by road needs ~36 min (implied 356 km/h)"},
  {"kind": "circling", "plate_text": "MH 05 DN 0114", "journey": "J03187", "index": 6, "camera_code": "VP-01", "time": "21:24:57", "evidence": [["VP-01", "21:05:39"], ["SC-01", "21:08:19"], ["VP-01", "21:12:27"], ["SC-01", "21:15:14"], ["VP-01", "21:18:51"], ["SC-01", "21:21:36"], ["VP-01", "21:24:57"]], "reason": "Suspicious circling: looped Vile Parle Flyover and Santacruz Airport Approach 3 times in 19 min with no destination"},
] as const;

/** Newest ANPR reads up to 2026-09-29T20:59:50+05:30 (the last watchlist hit), newest first. */
export const SIM_LIVE_FEED = [
  {"id": "lf-J03063-3", "plate": "MH 02 EG 9588", "cameraCode": "BH-01", "cameraName": "Bhandup LBS Marg", "vehicleType": "car", "plateVariant": "private", "confidence": 98, "secondsAgo": 0, "watchlist": "high"},
  {"id": "lf-J03174-0", "plate": "MH 01 YX 1306", "cameraCode": "KR-01", "cameraName": "Kurla Depot Junction", "vehicleType": "truck", "plateVariant": "commercial", "confidence": 95, "secondsAgo": 0, "watchlist": null},
  {"id": "lf-J03173-0", "plate": "MH 01 CY 3465", "cameraCode": "SC-01", "cameraName": "Santacruz Airport Approach", "vehicleType": "car", "plateVariant": "private", "confidence": 91, "secondsAgo": 5, "watchlist": null},
  {"id": "lf-J03162-1", "plate": "MH 01 NL 2930", "cameraCode": "AN-01", "cameraName": "Andheri Flyover (Gundavali)", "vehicleType": "motorcycle", "plateVariant": "private", "confidence": 85, "secondsAgo": 12, "watchlist": null},
  {"id": "lf-J03172-0", "plate": "MH 03 FP 2970", "cameraCode": "SN-01", "cameraName": "Sion Circle", "vehicleType": "car", "plateVariant": "private", "confidence": 84, "secondsAgo": 16, "watchlist": null},
  {"id": "lf-J03070-1", "plate": "MH 43 AK 2840", "cameraCode": "SC-01", "cameraName": "Santacruz Airport Approach", "vehicleType": "car", "plateVariant": "commercial", "confidence": 94, "secondsAgo": 18, "watchlist": null},
  {"id": "lf-J03171-0", "plate": "MH 47 GS 3266", "cameraCode": "SN-01", "cameraName": "Sion Circle", "vehicleType": "car", "plateVariant": "private", "confidence": 97, "secondsAgo": 45, "watchlist": null},
  {"id": "lf-J03151-2", "plate": "MH 03 BA 9133", "cameraCode": "SC-01", "cameraName": "Santacruz Airport Approach", "vehicleType": "car", "plateVariant": "commercial", "confidence": 86, "secondsAgo": 52, "watchlist": null},
] as const;

/** Sample pipeline plate reads per camera (plates really seen at that camera; real ANPR reads of its clip first). */
export const SIM_CAMERA_READS = [
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 01 CS 0126", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.78, "frame_sec": 2.7},
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 02 FR 7593", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.97, "frame_sec": 5.9},
  {"camera_id": "cam-001", "camera_code": "JG-01", "plate_text": "MH 01 EE 2085", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.96, "frame_sec": 9.9},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "MH 47 EL 9660", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.75, "frame_sec": 4.4},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "MH 02 GJ 3558", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.95, "frame_sec": 3.1},
  {"camera_id": "cam-002", "camera_code": "AN-01", "plate_text": "MH 03 EL 9982", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.95, "frame_sec": 14.1},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 02 EG 9588", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.73, "frame_sec": 2.5},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 02 FG 0919", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.98, "frame_sec": 28.3},
  {"camera_id": "cam-003", "camera_code": "VP-01", "plate_text": "MH 47 BF 5485", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.97, "frame_sec": 54.7},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 03 CM 7501", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.97, "frame_sec": 2.1},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 47 BL 6568", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.99, "frame_sec": 22.9},
  {"camera_id": "cam-004", "camera_code": "SC-01", "plate_text": "MH 14 JE 7336", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.99, "frame_sec": 31.9},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "MH 04 AK 4356", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.83, "frame_sec": 3.5},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "MH 01 EE 6661", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.98, "frame_sec": 9.4},
  {"camera_id": "cam-005", "camera_code": "DD-01", "plate_text": "MH 43 CJ 9870", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.97, "frame_sec": 9.3},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 47 AY 0208", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.97, "frame_sec": 30.9},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 02 FX 3138", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.95, "frame_sec": 26.3},
  {"camera_id": "cam-006", "camera_code": "SN-01", "plate_text": "MH 04 LE 7432", "vehicle_type": "truck", "plate_variant": "commercial", "confidence": 0.94, "frame_sec": 19.6},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "MH 01 EB 7023", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.98, "frame_sec": 28.1},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "MH 03 DG 7973", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.97, "frame_sec": 45.2},
  {"camera_id": "cam-007", "camera_code": "KR-01", "plate_text": "MH 03 EL 7427", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.94, "frame_sec": 21.3},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 05 EV 4710", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.99, "frame_sec": 4.9},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 50 U 1711", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.99, "frame_sec": 39.2},
  {"camera_id": "cam-008", "camera_code": "BH-01", "plate_text": "MH 03 EG 0770", "vehicle_type": "car", "plate_variant": "private", "confidence": 0.98, "frame_sec": 0.5},
] as const;
